eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 9999
  context-path: /labor
spring:
  application:
    name: feign-client
feign:
  hystrix:
      enabled: true