spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yelllong/config_center.git
          basedir: D:\JetBrains\workspace\gitRepository
server:
  port: 7777
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka